name: mg_diffuse
channels:
  - conda-forge
  - robostack-staging
dependencies:
  - python==3.9.0
  - numpy
  - matplotlib
  - tqdm
  - pytorch-cuda=11.8
  - einops
  - git
  - gitpython
  - scipy
  - notebook
  - gh
  - scikit-learn
  - pandas[version='>=1.2.0']
  - pip
  - pip:
    - -r requirements.txt
    - -e .
